const auditDir = require('fs').mkdirSync('docs/audit/final-run',{recursive:true});
const {chromium}=require('C:/Users/admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs');const assert=require('assert');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage();const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
for(const [width,height] of [[360,800],[390,844],[768,1024],[1024,768],[1440,900]])for(const route of ['','pages/about.html','pages/smart-farm.html','pages/products.html','pages/journey.html','pages/contact.html','pages/traceability.html?lot=UX-260915-01']){await page.setViewportSize({width,height});await page.goto('http://127.0.0.1:5500/'+route);await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){scrollTo(0,y);await new Promise(r=>setTimeout(r,25))}});await page.evaluate(async()=>{await Promise.all([...document.images].filter(i=>i.getAttribute("src")).map(async i=>{i.loading="eager";try{await i.decode()}catch{}}))});await page.waitForTimeout(350);const state=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].filter(i=>i.getAttribute('src')&&(!i.complete||!i.naturalWidth)).map(i=>i.src)}));results.push({width,route,...state});assert(!state.overflow,JSON.stringify(results.at(-1)));assert(!state.broken.length,JSON.stringify(results.at(-1)));}
await page.goto('http://127.0.0.1:5500/pages/products.html');assert.equal(await page.locator('.product-card').count(),10);for(const [filter,n] of [['microgreens',4],['leafy',3],['herbs',3],['all',10]]){await page.locator(`[data-filter="${filter}"]`).click();assert.equal(await page.locator('.product-card:visible').count(),n)}await page.locator('[data-product-id="5"]').click();assert(await page.locator('#product-modal').evaluate(e=>e.classList.contains('is-open')));await page.keyboard.press('Escape');
await page.goto('http://127.0.0.1:5500/pages/smart-farm.html');await page.locator('.farm-step').nth(3).click();assert((await page.locator('.farm-preview img').getAttribute('src')).includes('sensor-close'));
await page.goto('http://127.0.0.1:5500/');await page.locator('[data-motion]').scrollIntoViewIfNeeded();await page.locator('[data-motion-toggle]').click();assert(await page.locator('[data-motion]').evaluate(e=>e.classList.contains('is-paused')));await page.locator('[data-motion]').screenshot({path:'docs/audit/final-run/motion.png'});
await page.locator('#brand-video').scrollIntoViewIfNeeded();const film=await page.locator('video').evaluate(async v=>{await v.play();await new Promise(r=>setTimeout(r,1200));v.pause();const result={duration:v.duration,time:v.currentTime,muted:v.muted,volume:v.volume,tracks:v.textTracks.length,cues:v.textTracks[0]?.cues?.length,controls:v.controls};v.currentTime=16.5;return result});assert(film.duration>71&&film.duration<72);assert(film.time>0);assert.equal(film.tracks,0);await page.waitForTimeout(300);await page.locator('#video').screenshot({path:'docs/audit/final-run/video.png'});
await page.locator('.gallery-item').first().click();assert(await page.locator('.lightbox').evaluate(e=>e.classList.contains('is-open')));await page.keyboard.press('Escape');await page.locator('#gallery').screenshot({path:'docs/audit/final-run/gallery.png'});
for(const [width,height] of [[360,800],[1440,900]]){await page.setViewportSize({width,height});await page.goto('http://127.0.0.1:5500/');await page.waitForTimeout(1400);await page.screenshot({path:`docs/audit/final-run/final-home-${width}.png`});}
const nojs=await browser.newPage({javaScriptEnabled:false});await nojs.goto('http://127.0.0.1:5500/pages/products.html');assert.equal(await nojs.locator('.product-card:visible').count(),10);await nojs.close();
fs.writeFileSync('docs/audit/final-run/local-final.json',JSON.stringify({results,film,errors,checks:['filter','product modal','farm preview','motion pause','video playback/captions/seek','gallery lightbox','no-JS products']},null,2));console.log(JSON.stringify({results,film,errors}));await browser.close();assert.equal(errors.length,0);})();



