// Single authored catalog. Regenerate static cards with node tools/sync-products.mjs.
export const PRODUCTS = [
  {
    "id": 1,
    "name": "Microgreens hỗn hợp",
    "category": "microgreens",
    "tag": "Microgreens",
    "desc": "Nhiều sắc lá nhỏ trong cùng một phần rau, vị tươi và kết cấu nhẹ. Phù hợp khi bạn muốn khám phá hương vị đa dạng của microgreens.",
    "image": "assets/images/microgreens.webp",
    "features": "Hỗn hợp các loại microgreens",
    "flavor": "Tươi mát, hơi cay nhẹ, giòn",
    "usage": "Rau trộn, bánh mì, trang trí món ăn",
    "pairing": "Món có nhiều kết cấu, phần rau ăn kèm",
    "packaging": "Hộp 50 g hoặc 100 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  },
  {
    "id": 2,
    "name": "Microgreens cải củ đỏ",
    "category": "microgreens",
    "tag": "Microgreens",
    "desc": "Thân tím đỏ, lá xanh nhỏ và vị cay nhẹ tạo điểm nhấn dễ nhận ra. Một lựa chọn dành cho người thích món ăn có thêm cá tính.",
    "image": "assets/images/radish.webp",
    "features": "Thân tím đỏ, lá xanh nhỏ",
    "flavor": "Cay nhẹ, giòn, tươi",
    "usage": "Trang trí món ăn, rau trộn, sinh tố",
    "pairing": "Nguyên liệu vị thanh để làm nổi bật vị cay của rau",
    "packaging": "Hộp 50 g hoặc 100 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  },
  {
    "id": 3,
    "name": "Microgreens bông cải",
    "category": "microgreens",
    "tag": "Microgreens",
    "desc": "Thân mảnh, lá xanh nhỏ, hương vị dịu và hơi đắng nhẹ. Dễ kết hợp cùng những nguyên liệu có vị thanh để giữ nét riêng của rau.",
    "image": "assets/images/broccoli.webp",
    "features": "Thân mảnh, lá nhỏ xanh tươi",
    "flavor": "Nhẹ, hơi đắng, tươi",
    "usage": "Rau trộn, nước ép, ăn kèm",
    "pairing": "Món có nước xốt nhẹ, tránh lấn át hương rau",
    "packaging": "Hộp 50 g hoặc 100 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  },
  {
    "id": 4,
    "name": "Cải xoăn xanh",
    "category": "leafy",
    "tag": "Rau ăn lá",
    "desc": "Lá xanh có viền xoăn và kết cấu rõ, mang vị rau đậm. Thích hợp để cắt nhỏ, kết hợp trong món xào hoặc các món rau theo khẩu vị.",
    "image": "assets/images/kale.webp",
    "features": "Lá xanh, viền xoăn, kết cấu rõ",
    "flavor": "Đậm vị rau, hơi ngọt",
    "usage": "Rau trộn, sinh tố, xào nhanh",
    "pairing": "Món xào cùng nấm hoặc các loại rau theo mùa",
    "packaging": "Túi 250 g hoặc 500 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  },
  {
    "id": 5,
    "name": "Xà lách búp bơ",
    "category": "leafy",
    "tag": "Rau ăn lá",
    "desc": "Các lớp lá mềm ôm thành búp, vị thanh và giòn mát. Dáng lá thuận tiện cho món cuốn, bánh mì và đĩa rau ăn kèm.",
    "image": "assets/images/lettuce-product.webp",
    "features": "Lá mềm, giòn, màu xanh tươi",
    "flavor": "Ngọt nhẹ, mát",
    "usage": "Rau trộn, món cuốn, bánh mì",
    "pairing": "Món cuốn, bánh mì với phần nhân bạn yêu thích",
    "packaging": "Túi 250 g hoặc 500 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  },
  {
    "id": 6,
    "name": "Rau gia vị hỗn hợp",
    "category": "herbs",
    "tag": "Rau gia vị",
    "desc": "Húng quế, mùi tây và rau mùi mang những lớp hương riêng. Thêm từng ít một để tạo điểm nhấn mà vẫn giữ sự cân bằng cho món ăn.",
    "image": "assets/images/herbs.webp",
    "features": "Húng quế, mùi tây và rau mùi",
    "flavor": "Thơm mạnh, tươi sáng",
    "usage": "Nấu ăn, trang trí, đồ uống",
    "pairing": "Thêm từng loại theo mùi hương chủ đạo của món",
    "packaging": "Gói 50 g hoặc 100 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  },
  {
    "id": 7,
    "name": "Rau mầm đậu Hà Lan",
    "category": "microgreens",
    "tag": "Microgreens",
    "image": "assets/images/pea-shoots.webp",
    "desc": "Ngọn non có tua cuốn, vị đậu nhẹ và thân giòn. Một lựa chọn khác cho người muốn khám phá rau mầm.",
    "features": "Ngọn xanh, tua cuốn mảnh",
    "flavor": "Giòn, vị đậu nhẹ",
    "usage": "Rau mầm xào nấm, ăn kèm món nóng",
    "pairing": "Kết hợp cùng nấm hoặc đậu phụ",
    "packaging": "Hộp 50 g hoặc 100 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  },
  {
    "id": 8,
    "name": "Xà lách romaine",
    "category": "leafy",
    "tag": "Rau ăn lá",
    "image": "assets/images/romaine.webp",
    "desc": "Lá dài, gân rõ và kết cấu giòn. Phù hợp với món rau trộn hoặc cắt nhỏ dùng trong món cuốn.",
    "features": "Lá dài, gân giữa dày",
    "flavor": "Giòn, vị thanh",
    "usage": "Rau trộn, món cuốn, bánh mì",
    "pairing": "Kết hợp nước xốt theo khẩu vị",
    "packaging": "Túi 250 g hoặc 500 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  },
  {
    "id": 9,
    "name": "Húng quế",
    "category": "herbs",
    "tag": "Rau gia vị",
    "image": "assets/images/basil.webp",
    "desc": "Lá mềm và hương thơm rõ. Thêm một lượng nhỏ để món quen có thêm lớp hương riêng.",
    "features": "Lá xanh hình bầu dục, bề mặt tương đối nhẵn",
    "flavor": "Thơm, lá mềm",
    "usage": "Mì xốt húng quế, món xào, rau ăn kèm",
    "pairing": "Kết hợp cà chua hoặc món mì",
    "packaging": "Gói 50 g hoặc 100 g.",
    "storage": "Giữ lá khô ráo, tránh nắng và tránh làm dập. Làm theo hướng dẫn trên bao bì của lô hàng; rửa trước khi chế biến."
  },
  {
    "id": 10,
    "name": "Bạc hà",
    "category": "herbs",
    "tag": "Rau gia vị",
    "image": "assets/images/mint.webp",
    "desc": "Lá có mép răng cưa và mùi thơm mát. Dùng để tạo điểm nhấn cho món ăn hoặc đồ uống.",
    "features": "Lá có gân nổi, mép răng cưa",
    "flavor": "Thơm mát, lá mềm",
    "usage": "Trà bạc hà, nước chanh, món rau trộn",
    "pairing": "Kết hợp chanh hoặc trái cây",
    "packaging": "Gói 50 g hoặc 100 g.",
    "storage": "Giữ trong ngăn mát, tách khỏi thực phẩm sống; tránh nén hoặc để đọng nước. Làm theo hướng dẫn trên bao bì và rửa trước khi chế biến."
  }
];
